apiVersion: v1
kind: Pod
metadata:
  name: cloudweave-api
  labels:
    app: cloudweave-api
spec:
  containers:
    - name: api-container
      image: cloudweave/cloudweave-api:1.0
      ports:
        - containerPort: 8000