apiVersion: v1
kind: Pod
metadata:
  name: cloudweave-frontend
  labels:
    app: cloudweave-frontend
spec:
  containers:
    - name: frontend-container
      image: bruno7317/cloudweave-frontend:1.0
      ports:
        - containerPort: 3000
