apiVersion: v1
kind: Pod
metadata:
  name: cloudweave-frontend
  labels:
    app: cloudweave-frontend
spec:
  containers:
    - name: frontend-container
      image: node:lts
      command: ["tail"]
      args: ["-f", "/dev/null"]
      ports:
        - containerPort: 80
