apiVersion: v1
kind: Pod
metadata:
  name: mongodb-api
  labels:
    app: mongodb-api
spec:
  containers:
    - name: mongodb-container
      image: node:lts
      command: ["tail"]
      args: ["-f", "/dev/null"]
      envFrom:
        - configMapRef:
          name: mongodb-configmap