apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-api
  labels:
    app: postgresdb-api
spec:
  containers:
    - name: postgresdb-container
      image: node:lts
      command: ["tail"]
      args: ["-f", "/dev/null"]