apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudweave
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bruno7317/cloudweave-infra
    targetRevision: master
    path: k8s/cloudweave
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudweave
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
