apiVersion: v1
kind: Pod
metadata:
  name: cloudweave-api
  labels:
    app: cloudweave-api
spec:
  containers:
    - name: api-container
      image: 373609202462.dkr.ecr.ca-central-1.amazonaws.com/cloudweave-api:1.0
      ports:
        - containerPort: 8000