apiVersion: v1
kind: Pod
metadata:
  name: cloudweave-frontend
  namespace: default
  labels:
    app: cloudweave-frontend
spec:
  containers:
    - name: frontend-container
      image: 373609202462.dkr.ecr.ca-central-1.amazonaws.com/cloudweave-frontend:1.0
      ports:
        - containerPort: 3000
