apiVersion: v1
kind: Pod
metadata:
  name: mongodb-api
  labels:
    app: mongodb-api
spec:
  containers:
    - name: mongodb-container
      image: 373609202462.dkr.ecr.ca-central-1.amazonaws.com/mongo-api:latest
      ports:
        - containerPort: 7000
      envFrom:
        - configMapRef:
            name: mongodb-configmap