apiVersion: v1
kind: Pod
metadata:
  name: postgresdb-api
  labels:
    app: postgresdb-api
spec:
  containers:
    - name: postgresdb-container
      image: 373609202462.dkr.ecr.ca-central-1.amazonaws.com/postgres-api:latest
      ports:
        - containerPort: 6000
      envFrom:
        - configMapRef:
            name: postgresdb-configmap